Fixes tests
chainer/chainerrl pull request #605
Opened 2020-11-15 17:29 UTC by prabhatnagarajan

2020-11-15 17:30 UTC, prabhatnagarajan commented
/test

2020-11-16 02:58 UTC, prabhatnagarajan commented
/test

2020-11-16 03:16 UTC, prabhatnagarajan commented
/test

2020-11-16 03:25 UTC, prabhatnagarajan commented
/test

2020-11-16 03:45 UTC, prabhatnagarajan commented
/test

2020-11-16 04:26 UTC, prabhatnagarajan commented
/test

2020-11-16 05:02 UTC, prabhatnagarajan commented
/test

2020-11-16 06:18 UTC, prabhatnagarajan commented
/test

2020-11-16 08:00 UTC, prabhatnagarajan commented
/test

2020-11-16 08:00 UTC, prabhatnagarajan commented on examples/grasping/train_dqn_batch_grasping.py
> -        assert env.observation_space is None
I removed this line after this recent update to the environment: https://github.com/bulletphysics/bullet3/commit/3a6a279b9a757c4c1306fc55fa6e95df40c89574#diff-37edfb1b0750fd6a650da86f2d5c1ec3827623de1abb22ba2fc7cf897eeb5c44

2020-11-18 01:47 UTC, muupan requested changes

2020-11-18 01:47 UTC, muupan commented on examples/atari/reproduction/a3c/train_a3c.py
> -
You should not move this line. This must be done before `import numpy`.

2020-11-18 01:47 UTC, muupan commented on examples/atari/train_a3c_ale.py
> -
Ditto

2020-11-18 01:47 UTC, muupan commented on examples/atari/train_acer_ale.py
> -
Ditto

2020-11-18 01:47 UTC, muupan commented on examples/atari/train_nsq_ale.py
> -
Ditto

2020-11-18 01:47 UTC, muupan commented on examples/gym/train_a3c_gym.py
> -
Ditto

2020-11-18 01:47 UTC, muupan commented on examples/gym/train_acer_gym.py
> -
Ditto

2020-11-18 01:47 UTC, muupan commented on examples/gym/train_pcl_gym.py
> -
Ditto

2020-11-18 01:48 UTC, muupan commented
Can you explain why it needs python 3.6?

2020-11-18 04:06 UTC, prabhatnagarajan commented
Some of the previous PR CIs were failing:
https://ci.preferred.jp/chainerrl.py3.cpu/62915/
```
2020-09-16 16:48:46.403755 STDOUT 2092] | Downloading https://files.pythonhosted.org/packages/53/10/776750d57ade26522478a92a2e14035868624a6a62f4157b0cc5abd4a980/scipy-1.5.2.tar.gz (25.4MB) | 5.1s
-- | -- | --
2020-09-16 16:48:51.473617 STDOUT 2092] | Complete output from command python setup.py egg_info: |  
2020-09-16 16:48:51.473630 STDOUT 2092] | Traceback (most recent call last): |  
2020-09-16 16:48:51.473644 STDOUT 2092] | File "<string>", line 1, in <module> |  
2020-09-16 16:48:51.473747 STDOUT 2092] | File "/tmp/pip-build-sxosch92/scipy/setup.py", line 31, in <module> |  
2020-09-16 16:48:51.473749 STDOUT 2092] | raise RuntimeError("Python version >= 3.6 required.") |  
2020-09-16 16:48:51.473756 STDOUT 2092] | RuntimeError: Python version >= 3.6 required.
```

I thought it would be ok to update the required version to 3.6 (at least for testing).

2020-11-19 03:34 UTC, prabhatnagarajan commented
/test

2020-11-19 05:05 UTC, prabhatnagarajan commented
/test

2020-11-19 05:42 UTC, prabhatnagarajan commented
/test

2020-11-25 02:36 UTC, muupan approved these changes
While E402 can be addressed in a different way (https://gitlab.com/pycqa/flake8/-/issues/638), I think it is good to merge as it is since fixing the CI asap is important.

2020-11-25 02:37 UTC, merged